.TH {{name}} 1 {{date}} v{{version}}
.SH NAME
{{name}}
.SH SYNOPSIS
{{synopsis}}
.SH DESCRIPTION
{{description}}
.SH OPTIONS
{{options}}
.SH EXAMPLES
{{examples}}
.SH BUGS
.SH SEE ALSO
.SH AUTHOR
Anadian ( https://github.com/Anadian )
.SH COPYRIGHT
Code license: MIT
Documentation license: Creative Commons Atribution-ShareAlike 4.0 International License
